machine:
  php:
    version: 5.6

test:
  pre: 
    - echo "-----start test-----"
  override:    
    - go test -cover  
    - php test1.php
  post: 
    - echo "-----end test-----"

deployment:
  deploy:
    branch: master
    commands:
      - make build
      - make deploy

