test:
  pre: 
    - echo "-----start test-----"
  override:    
    - go test -cover  
  post: 
    - echo "-----end test-----"

deployment:
  deploy:
    branch: master
    commands:
      - make build
      - make deploy

